apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Service
metadata:
  name: istio
  namespace: istio-system
  labels:
    app: istio
spec:
  type: LoadBalancer
  selector:
    app: istio
  ports:
  - name: http2
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio
  template:
    metadata:
      labels:
        app: istio
    spec:
      serviceAccountName: istio
      containers:
      - name: istio
        # Pinned to latest verified version, as this is changing rapidly
        image: gcr.io/istio-testing/pilot:1.6-alpha.880a8ff5bceba6ae5f4f86a5adf137a91ae7265a
        imagePullPolicy: Always
        args:
        - discovery
        env:
        - name: PILOT_ENABLED_SERVICE_APIS
          value: "true"  # This will be enabled by default in th future
      - name: proxy
        image: gcr.io/istio-testing/proxyv2:1.6-alpha.880a8ff5bceba6ae5f4f86a5adf137a91ae7265a
        args:
        - proxy
        - router
        env:
        - name: MESH_CONFIG
          value: |-
            defaultConfig:
              discoveryAddress: localhost:15010
        - name: ISTIO_META_CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio
  namespace: istio-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["services", "nodes", "pods", "endpoints", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "get", "list", "watch"]
- apiGroups: ["networking.x.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.x.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# Pilot will try to read these even if they aren't existing. For now, just give access.
- apiGroups:
  - config.istio.io
  - networking.istio.io
  - authentication.istio.io
  - rbac.istio.io
  - security.istio.io
  resources: ["*"]
  verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: istio
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: istio
  apiGroup: rbac.authorization.k8s.io
