apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  class: istio
  listeners:
  - hostname:
      match: Exact
      name: gateway.local
    port: 80
    protocol: HTTP
    routes:
      resource: httproutes
      routeNamespaces:
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          istio.io/gateway: gateway
  - hostname:
      match: Exact
      name: gateway.local
    port: 443
    protocol: HTTPS
    routes:
      resource: httproutes
      routeNamespaces:
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          istio.io/gateway: gateway
    tls:
      certificateRefs:
      - name: service-apis-cert
      options: {}
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: http
  namespace: service-apis-demo
  labels:
    istio.io/gateway: gateway
spec:
  hosts:
  - hostnames: ["gateway.local"]
    rules:
    - match:
        pathMatchType: Prefix
        path: /get
      filter:
        headers:
          add:
            my-added-header: added-value
          remove: [my-removed-header]
      action:
        forwardTo:
        - targetPort: 80
          targetRef:
            name: httpbin
