apiVersion: v1
kind: Namespace
metadata:
  name: corp
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: corp
spec:
  class: istio
  listeners:
  - hostname:
      match: Any
    port: 80
    protocol: HTTP
    routes:
      resource: httproutes
      routeNamespaces:
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          app: zoneprinter
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-route-team1
  namespace: team1
  labels:
    app: zoneprinter
spec:
  hosts:
  - hostnames: [team1.example.com]
    rules:
    - match:
        pathMatchType: Prefix
        path: /
        headerMatchType: Exact
        headers:
          env: stage
      action:
        forwardTo:
        - targetRef:
            name: zoneprinter-v2
            resource: services
    - match:
        pathMatchType: Prefix
        path: /
        headerMatchType: Exact
        headers:
          env: canary
      action:
        forwardTo:
        - targetRef:
            name: zoneprinter-v1
            resource: services
          weight: 80
        - targetRef:
            name: zoneprinter-v2
            resource: services
          weight: 20
    - match:
        pathMatchType: Prefix
        path: /
      action:
        forwardTo:
        - targetRef:
            name: zoneprinter-v1
            resource: services
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-route-team2
  namespace: team2
  labels:
    app: zoneprinter
spec:
  hosts:
  - hostnames: [team2.example.com]
    rules:
      - match:
          pathMatchType: Prefix
          path: /
        action:
          forwardTo:
          - targetRef:
              name: zoneprinter-v1
              resource: services
