apiVersion: v1
kind: Namespace
metadata:
  name: corp
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: corp
spec:
  class: istio
  listeners:
  - hostname:
      match: Any
    port: 80
    protocol: HTTP
    routes:
      namespaceSelector: {}
      routeSelector:
        matchLabels:
          app: zoneprinter
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
 name: http-route-team1
 namespace: team1
 labels:
   app: zoneprinter
spec:
 hosts:
   - hostname: team1.example.com
     rules:
       - match:
           pathType: Prefix
           path: /
           headerType: Exact
           header:
             env: stage
         action:
           forwardTo:
             targetRef:
               name: zoneprinter-v2
               resource: services
               group: ""
       - match:
           pathType: Prefix
           path: /
         action:
           forwardTo:
             targetRef:
               name: zoneprinter-v1
               resource: services
               group: ""
 default:
   rules:
     - action:
         forwardTo:
           targetRef:
             name: zoneprinter-v1
             resource: services
             group: ""
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
 name: http-route-team2
 namespace: team2
 labels:
   app: zoneprinter
spec:
 hosts:
   - hostname: team2.example.com
     rules:
       - match:
           pathType: Prefix
           path: /
         action:
           forwardTo:
             targetRef:
               name: zoneprinter-v1
               resource: services
               group: ""
 default:
   rules:
     - action:
         forwardTo:
           targetRef:
             name: zoneprinter-v1
             resource: services
             group: ""
